name: md_messenger
description: Messanging App 


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0
  stream_chat_flutter: ^1.5.2
  cupertino_icons: ^1.0.2
  drag_to_expand: ^0.0.1
  http: ^0.12.0
  flutter_secure_storage: ^4.2.0
  loading: ^1.0.2
  loading_indicator: ^2.1.1
  google_fonts: ^1.1.2
  flutter_spinkit: ^4.1.2

  


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/